### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by GledsonAfonso**
-Fixing files references;
-Adding some markdown.

### CODE REVIEW

**Comment by stokito** [comment]
This is a mirror of repository and is read only. See https://openjdk.java.net/contribute/ about how to contribute. You need to sign  Oracle Contributor Agreement - without this none of your changes will be merged

**Comment by GledsonAfonso** [comment]
Thanks for the heads up @stokito ! I will see into that.

**Comment by edvbld** [comment]
Hi @GledsonAfonso, thanks for your PR. As @stokito mentioned, this respository is a read-only mirror of the upstream sources available at https://hg.openjdk.java.net/jdk/jdk. If you want to contribute to OpenJDK, please see https://openjdk.java.net/contribute/ on how to get started.

If you need any help to get started contributing, please join the IRC channel `#opendjk` at irc.oftc.net.

**Comment by GledsonAfonso** [comment]
Thanks @edvbld! I hope one day I can contribute to the project. Cheers!

**Pull request closed without merging**
